name: Build and Deploy Windows Container App to Azure App Service

# Trigger the build on commits into the master branch
on:
  push:
    branches:
      - main

# Starts jobs and sets the type of runner (Windows) they will run on
jobs:
  build-and-deploy-to-azure:
    runs-on: windows-2016

    steps:

    # Checks out repository so your workflow can access it
    - uses: actions/checkout@v1
    - name: build project
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)